mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: im.peng.ceramic.ceramic_sell.model.po

server:
  port: 8181
  servlet:
    context-path: /seramic

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seramic_sell?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true